server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    allocation-message-receiver: /allocation-message-receiver/**
    confirmation-service: /confirmation-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO